openapi: 3.0.2
info:
  contact:
    email: sales@ziqni.com
    name: Sales
    url: https://www.ziqni.com
  description: Webhook subscriber services intended use is to assist in the creation
    of a subscriber service.
  license:
    name: Proprietary and confidential
  title: ZIQNI Webhook Services
  version: 3.0.0
externalDocs:
  description: Find out more about Ziqni
  url: https://www.ziqni.com
servers:
- description: Your server endpoint
  url: https://your.server.com
tags:
- description: Perform REST operations on Webhooks
  name: webhooks
paths:
  /ziqni/webhook:
    post:
      description: Example server implementation used to subscribe to webhooks
      operationId: onWebhook
      parameters:
      - description: gzip
        explode: false
        in: header
        name: Accept-Encoding
        required: false
        schema:
          default: gzip
          type: string
        style: simple
      - description: ZIQNI/1.0
        explode: false
        in: header
        name: User-Agent
        required: false
        schema:
          default: Ziqni/1.0
          type: string
        style: simple
      - description: Unique identifier of your account
        explode: false
        in: header
        name: X-Account
        required: false
        schema:
          type: string
        style: simple
      - description: depending which webhook you are selecting
        explode: false
        in: header
        name: X-OnEvent
        required: false
        schema:
          enum:
          - onAchievementCreated
          - onAchievementRewardIssued
          - onAchievementTriggered
          - onCompetitionCreated
          - onCompetitionStarted
          - onCompetitionFinished
          - onCompetitionCancelled
          - onCompetitionRewardIssued
          - onContestCreated
          - onContestStarted
          - onContestFinished
          - onContestFinalised
          - onContestCancelled
          - onContestRewardIssued
          - onNewMember
          - onNewProduct
          type: string
        style: simple
      - description: Event type code
        explode: false
        in: header
        name: X-Event
        required: false
        schema:
          type: string
        style: simple
      - description: 'The identifier of this webhook '
        explode: false
        in: header
        name: X-WebhookId
        required: false
        schema: {}
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookRequestBody'
        description: Retrieve Products from Ziqni database by unique Product ID's
          or any other POST body parameters using the POST method
      responses:
        "200":
          description: A webhook was triggered successfully
        "400":
          content:
            application/json:
              examples:
                Example Value:
                  $ref: '#/components/examples/GetErrorResponse'
              schema:
                $ref: '#/components/schemas/Response'
          description: Bad Request
        "401":
          content:
            application/json:
              examples:
                Example Value:
                  $ref: '#/components/examples/GetErrorResponse'
              schema:
                $ref: '#/components/schemas/Response'
          description: Unauthorized
        "403":
          content:
            application/json:
              examples:
                Example Value:
                  $ref: '#/components/examples/GetErrorResponse'
              schema:
                $ref: '#/components/schemas/Response'
          description: Forbidden
        "404":
          content:
            application/json:
              examples:
                Example Value:
                  $ref: '#/components/examples/GetErrorResponse'
              schema:
                $ref: '#/components/schemas/Response'
          description: The specified resource was not found
        "405":
          content:
            application/json:
              examples:
                Example Value:
                  $ref: '#/components/examples/GetErrorResponse'
              schema:
                $ref: '#/components/schemas/Response'
          description: Method not allowed
        "500":
          content:
            application/json:
              examples:
                Example Value:
                  $ref: '#/components/examples/GetErrorResponse'
              schema:
                $ref: '#/components/schemas/Response'
          description: Internal server error
        "503":
          content:
            application/json:
              examples:
                Example Value:
                  $ref: '#/components/examples/GetErrorResponse'
              schema:
                $ref: '#/components/schemas/Response'
          description: Service unavailable
      security:
      - adminApiKey: []
      summary: Handle notifications
      tags:
      - webhooks
      x-codegen-request-body-name: body
      x-eov-operation-handler: controllers/WebhooksController
components:
  examples:
    GetErrorResponse:
      summary: Example Value
      value:
        meta:
          resultCount: 0
          errorCount: 1
          skip: 0
          limit: 100
        results: []
        errors:
        - errorCode: 1007
          message: The error was caused by an invalid ID being submitted
          detail: []
  schemas:
    Response:
      properties:
        errors:
          items:
            $ref: '#/components/schemas/Error'
          type: array
      required:
      - results
      type: object
    Error:
      properties:
        modelId:
          description: The identifier of the record this error relates to (This value
            only gets set if the error could relate to more than one object)
          example: 1234abc
          type: string
        errorCode:
          description: A unique system identifier that describes this specific error.
          example: 1007
          type: integer
        message:
          description: The error description.
          example: The error was caused by an invalid ID being submitted
          type: string
      required:
      - errorCode
      - message
    WebhookRequest:
      description: ""
      properties:
        accountId:
          description: ""
          type: string
        headers:
          additionalProperties:
            type: string
          type: object
        postToUrl:
          description: ""
          type: string
        auth:
          additionalProperties:
            type: string
          type: object
        body:
          $ref: '#/components/schemas/WebhookRequestBody'
        onEventType:
          description: ""
          type: string
      required:
      - accountId
      - body
      - headers
      - onEventType
      - postToUrl
      type: object
    OptParamModels:
      properties:
        metadata:
          additionalProperties:
            type: string
          type: object
        objectType:
          description: ""
          type: string
        constraints:
          description: "Constraints applied to this object, like hasRewards etc."
          items:
            type: string
          type: array
        accountId:
          description: The account identifier
          type: string
        spaceName:
          description: The space name
          type: string
      required:
      - accountId
      - objectType
      - spaceName
      type: object
    AchievementRewardIssued:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/Award'
      - $ref: '#/components/schemas/AchievementRewardIssued_allOf'
    AchievementRewardCreated:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/Reward'
      - $ref: '#/components/schemas/AchievementRewardIssued_allOf'
    AchievementRewardClaimed:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/Award'
      - $ref: '#/components/schemas/AchievementRewardIssued_allOf'
    AchievementTriggered:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/AchievementTriggered_allOf'
    AchievementCreated:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/AchievementRewardIssued_allOf'
    CompetitionCancelled:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/CompetitionCancelled_allOf'
    CompetitionCreated:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/CompetitionCreated_allOf'
    CompetitionFinished:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/CompetitionCancelled_allOf'
    CompetitionRewardIssued:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/Award'
      - $ref: '#/components/schemas/CompetitionCancelled_allOf'
    CompetitionStarted:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/CompetitionCancelled_allOf'
    ContestCreated:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/ContestCreated_allOf'
    ContestFinalised:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/ContestCreated_allOf'
    ContestFinished:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/ContestCreated_allOf'
    ContestRewardClaimed:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/Award'
      - $ref: '#/components/schemas/ContestCreated_allOf'
    ContestRewardCreated:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/Reward'
      - $ref: '#/components/schemas/ContestCreated_allOf'
    ContestRewardIssued:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/Award'
      - $ref: '#/components/schemas/ContestCreated_allOf'
    ContestStarted:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/ContestCreated_allOf'
    NewMember:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/NewMember_allOf'
    NewProduct:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/NewProduct_allOf'
    Reward:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/Reward_allOf'
      description: ""
      required:
      - entityId
      - rewardId
      - rewardTypeId
      - rewardTypeKey
      - value
      type: object
    Award:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/Award_allOf'
      description: ""
      required:
      - entityId
      - rewardId
      - rewardTypeId
      - rewardTypeKey
      - value
      type: object
    WebhookRequestBody:
      description: ""
      discriminator:
        propertyName: objectType
      oneOf:
      - $ref: '#/components/schemas/NewProduct'
      - $ref: '#/components/schemas/NewMember'
      - $ref: '#/components/schemas/CompetitionCreated'
      - $ref: '#/components/schemas/CompetitionStarted'
      - $ref: '#/components/schemas/CompetitionFinished'
      - $ref: '#/components/schemas/CompetitionCancelled'
      - $ref: '#/components/schemas/CompetitionRewardIssued'
      - $ref: '#/components/schemas/ContestCreated'
      - $ref: '#/components/schemas/ContestStarted'
      - $ref: '#/components/schemas/ContestFinished'
      - $ref: '#/components/schemas/ContestFinalised'
      - $ref: '#/components/schemas/ContestCancelled'
      - $ref: '#/components/schemas/ContestRewardCreated'
      - $ref: '#/components/schemas/ContestRewardIssued'
      - $ref: '#/components/schemas/ContestRewardClaimed'
      - $ref: '#/components/schemas/AchievementCreated'
      - $ref: '#/components/schemas/AchievementTriggered'
      - $ref: '#/components/schemas/AchievementRewardCreated'
      - $ref: '#/components/schemas/AchievementRewardIssued'
      - $ref: '#/components/schemas/AchievementRewardClaimed'
    ContestCancelled:
      allOf:
      - $ref: '#/components/schemas/OptParamModels'
      - $ref: '#/components/schemas/ContestCreated_allOf'
    AchievementRewardIssued_allOf:
      properties:
        achievementId:
          description: Achievement identifier
          type: string
        achievementName:
          description: First 120 characters of the default name
          type: string
      required:
      - achievementId
      type: object
      example: null
    AchievementTriggered_allOf:
      properties:
        achievementId:
          description: Achievement identifier
          type: string
        memberId:
          description: Member identifier
          type: string
        memberRefId:
          description: Member Reference id
          type: string
        achievementName:
          description: First 120 characters of the default name
          type: string
      type: object
      example: null
    CompetitionCancelled_allOf:
      properties:
        competitionId:
          description: Competition identifier
          type: string
        competitionName:
          description: First 120 characters of the default name
          type: string
      required:
      - competitionId
      type: object
      example: null
    CompetitionCreated_allOf:
      properties:
        competitionId:
          description: Competition identifier
          type: string
        competitionName:
          description: First 120 characters of the default name
          type: string
      type: object
      example: null
    ContestCreated_allOf:
      properties:
        contestId:
          description: Contest identifier
          type: string
        contestName:
          description: First 120 characters of the default name
          type: string
      required:
      - contestId
      type: object
      example: null
    NewMember_allOf:
      properties:
        memberId:
          description: Member identifier
          type: string
        memberRefId:
          description: Member Reference id
          type: string
        memberName:
          description: First 120 characters of the default name
          type: string
      required:
      - memberId
      type: object
      example: null
    NewProduct_allOf:
      properties:
        productId:
          description: Product identifier
          type: string
        productRefId:
          description: Product Reference id
          type: string
        productName:
          description: First 120 characters of the default name
          type: string
      required:
      - productId
      type: object
      example: null
    Reward_allOf:
      properties:
        rewardId:
          description: ""
          type: string
        entityId:
          description: ""
          type: string
        rewardTypeKey:
          description: ""
          type: string
        rewardTypeId:
          description: ""
          type: string
        value:
          description: ""
          format: double
          type: number
        rewardName:
          description: First 120 characters of the default name
          type: string
      required:
      - entityId
      - rewardId
      - rewardTypeId
      - rewardTypeKey
      - value
      example: null
    Award_allOf:
      properties:
        awardId:
          description: ""
          type: string
        rewardId:
          description: ""
          type: string
        rewardTypeKey:
          description: ""
          type: string
        rewardTypeId:
          description: ""
          type: string
        rewardMetaData:
          additionalProperties:
            type: string
          type: object
        value:
          description: ""
          format: double
          type: number
        memberRefId:
          description: Member Reference id
          type: string
        memberId:
          description: Member id
          type: string
        rewardName:
          description: Firtst 120 characters of the default name
          type: string
      required:
      - awardId
      - entityId
      - rewardId
      - rewardTypeId
      - rewardTypeKey
      - value
      example: null
  securitySchemes:
    adminApiKey:
      description: The admin API Key generated from Ziqni back office.
      in: header
      name: X-API-KEY
      type: apiKey
